app/models.py
from datetime import datetime
from decimal import Decimal

from sqlalchemy import String, Numeric, DateTime, Integer
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(String(120), index=True, unique=True)
    password_hash = db.Column(String(128))
    balance = db.Column(Numeric(6, 2))
    created_date = db.Column(DateTime)
    updated_date = db.Column(DateTime)

    def __repr__(self):
        return '<Email {}>'.format(self.email)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password) -> bool:
        return check_password_hash(self.password_hash, password)

    def add_transaction(self,
                        txn_type: str,
                        txn_amount: Decimal,
                        current_balance: Decimal,
                        date=datetime.utcnow()):
        txn = Transaction(user_id=self.id,
                          txn_amount=txn_amount,
                          current_balance=current_balance,
                          txn_type=txn_type,
                          date=date)

        txn.add()

    @staticmethod
    def find_by_email(email):
        return db.session.query(User).filter(User.email == email).one()

    @staticmethod
    def update_balance(email, balance):
        user = db.session.query(User).with_lockmode('update').filter(User.email == email).one()
        user.balance = balance
        user.updated_date = datetime.utcnow()
        db.session.commit()


class Transaction(db.Model):
    id = db.Column(Integer, primary_key=True)
    user_id = db.Column(Integer, nullable=False)
    txn_amount = db.Column(Numeric(6, 2), nullable=False)
    current_balance = db.Column(Numeric(6, 2), nullable=False)
    txn_type = db.Column(String(20), nullable=False)
    date = db.Column(DateTime, nullable=False)

    def add(self):
        db.session.add(self)
        db.session.commit()

    @staticmethod
    def list(user_id: Integer, limit: int = 10):
        return (Transaction.query
                .filter_by(user_id=user_id)
                .order_by(Transaction.date.desc())
                .limit(limit)
                .all())

app/account/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField
from wtforms.fields.html5 import DecimalField
from wtforms.validators import DataRequired


class AccountForm(FlaskForm):
    amount = DecimalField(places=2, validators=[DataRequired()])
    submit = SubmitField(label='Submit')

app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, HiddenField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    next_page = HiddenField('next')
    submit = SubmitField('Sign In')

app/__init__.py
import logging
import os

from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from app import logger

logger.configure(level=os.getenv('LOG_LEVEL', logging.INFO))
log = logging.getLogger(__name__)
logging.getLogger('werkzeug').setLevel(logging.INFO)
logging.getLogger('botocore').setLevel(logging.INFO)

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()


def create_app():
    app = Flask(__name__)
    app.config.from_object(os.environ['APP_SETTINGS'])

    # database and migration
    db.init_app(app)
    migrate.init_app(app, db)
    migration_setup()

    # security
    login.init_app(app)
    login.login_view = 'home.login'
    # Workaround for issue https://github.com/maxcountryman/flask-login/issues/419
    login.login_message_category = 'login.message'

    register_error_handler(app)
    register_blueprints(app)

    log.info("App Setup complete")

    return app


def migration_setup():
    from app import models


def register_error_handler(app: Flask):
    from app.errors import errors_view
    app.register_blueprint(errors_view)


def register_blueprints(app: Flask):
    # BluePrints and models need db, so imports cannot be before creating the db
    from app.home import home_view
    from app.account import account_view

    app.register_blueprint(home_view)
    app.register_blueprint(account_view)

    log.info("Blueprints registered")

app/account/__init__.py
from flask import Blueprint

account_view = Blueprint('account', __name__,
                         url_prefix='/account')

from app.account import views

app/account/views.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_required

from app.account import account, account_view
from app.account.forms import AccountForm


@account_view.route('/debit', methods=['GET', 'POST'])
@login_required
def debit():
    form = AccountForm()
    if form.validate_on_submit():
        transaction = account.record_debit(form.amount.data)
        flash(f'{transaction.amount} debited successfully.')
        return redirect(url_for('account.debit'))
    else:
        return render_debit(form=form)


@account_view.route('/credit', methods=['GET', 'POST'])
@login_required
def credit():
    form = AccountForm()
    if form.validate_on_submit():
        transaction = account.record_credit(form.amount.data)
        flash(f'{transaction.amount} credited successfully.')
        return redirect(url_for('account.credit'))
    else:
        return render_credit(form=form)


def render_credit(form: AccountForm):
    return render_template('credit.html', form=form,
                           currentBalance=account.formatted_balance(),
                           transactions=account.transactions())


def render_debit(form: AccountForm):
    return render_template('debit.html', form=form,
                           currentBalance=account.formatted_balance(),
                           transactions=account.transactions())

app/home/__init__.py
from flask import Blueprint

home_view = Blueprint('home', __name__,
                      url_prefix='/home')

from app.home import views

app/home/views.py
from flask import render_template, redirect, url_for, request
from flask_login import current_user, login_user, logout_user

from app.home import user, home_view
from app.home.forms import LoginForm
from app.url_util import is_safe_url


@home_view.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('account.debit'))

    form = LoginForm(next_page='')

    if request.method == 'GET':
        form.next_page.data = request.args.get('next')

    if form.validate_on_submit():
        authenticated_user = user.authenticate(form.username.data, form.password.data)

        if authenticated_user:
            next_page = form.next_page.data

            if not is_safe_url(next_page):
                next_page = None

            login_user(authenticated_user)
            return redirect(next_page or url_for('account.debit'))

        else:
            return _render_login(LoginForm(next_page=''), error='Please check your username and password')

    return _render_login(form)


@home_view.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home.login'))


def _render_login(form: LoginForm, error: str = None):
    return render_template('login.html',
                           title='Login',
                           form=form,
                           error=error)

app/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div>
        {% with messages = get_flashed_messages(category_filter=["message"]) %}
            {% if messages %}
                <div class="alert alert-success" role="alert">
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}
    </div>

    <div class="border border-dark rounded p-4">
        <form method="post" action="{% block url %}{% endblock %}" class="center" novalidate>
            <div class="form-group">
                <div class="form-group">
                    <label for="amount">{% block accountLabel %}{% endblock %}</label>
                    {{ form.amount(class_='form-control', **{'aria-describedby':'amountHelp'}) }}
                    {% for error in form.amount.errors %}
                        <small id="amountHelp" class="form-text text-danger">[{{ error }}]</small>
                    {% endfor %}

                </div>
            </div>
            {{ form.hidden_tag() }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <hr class="my-4">

    <div class="shadow-sm p-3 mb-4 bg-info rounded">You have {{ currentBalance }}</div>

    <h4 class="display-6">Transaction Summary</h4>


    <table class="table mb-3">
        <thead class="thead-light">
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Amount</th>
            <th scope="col">Balance</th>
        </tr>
        </thead>
        <tbody>
        {% for txn in transactions %}

            <tr>
                <td>{{ txn.date }}</td>

                {% if txn.type == 'DEBIT' %}
                    <td class="text-danger">- {{ txn.amount }}</td>
                {% else %}
                    <td class="text-success">+ {{ txn.amount }}</td>
                {% endif %}

                <td>{{ txn.balance }}</td>
            </tr>

        {% endfor %}
        </tbody>
    </table>

{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ url_for('home.login') }}">WeBank</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('account.debit') }}">Debit</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('account.credit') }}">Credit</a>
            </li>
        </ul>
        <span class="nav-item active my-2 my-lg-0">
            <a class="nav-link text-light" href="{{ url_for('home.logout') }}">Logout</a>
        </span>
    </div>
</nav>
<div class="jumbotron">
    <h1 class="display-6">WeBank</h1>
    <p class="lead">Credit is what comes in and Debit is what goes out, from a single user and largest account...</p>
    <hr class="my-4">
    <p>This a simple flask example of Banking Kata implementation</p>
    <a class="btn btn-primary btn-lg" href="http://kata-log.rocks/banking-kata" role="button" target="_blank">Learn
        more</a>
</div>
<main role="main" class="container">
    {% block content %}{% endblock %}
</main>
<footer class="footer">
    <div class="container">
        <span class="text-muted">WeBank Copyright 2018</span>
    </div>
</footer>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/credit.html
{% extends "account.html" %}
{% block title %}Credit{% endblock %}
{% block url %}{{ url_for('account.credit') }}{% endblock %}
{% block accountLabel %}Amount To Be Credited{% endblock %}

app/templates/debit.html
{% extends "account.html" %}
{% block title %}Debit{% endblock %}
{% block url %}{{ url_for('account.debit') }}{% endblock %}
{% block accountLabel %}Amount To Be Debited{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block content %}
    {% if error %}
        <div class="alert alert-warning" role="alert">
            {{ error }}
        </div>
    {% endif %}

    <div class="border border-dark rounded p-4">
        <form method="post" action="{{ url_for('home.login') }}" class="center" novalidate>
            <div class="form-group">
                {{ form.username.label }}
                {{ form.username(size=32, class_='form-control', **{'aria-describedby':'emailHelp'}) }}
                {% for error in form.username.errors %}
                    <small id="emailHelp" class="form-text text-danger">[{{ error }}]</small>
                {% endfor %}

            </div>
            <div class="form-group">
                {{ form.password.label }}
                {{ form.password(size=32, class_='form-control', **{'aria-describedby':'passwordHelp'}) }}
                {% for error in form.password.errors %}
                    <small id="passwordHelp" class="form-text text-danger">[{{ error }}]</small>
                {% endfor %}
            </div>
            {{ form.hidden_tag() }}
            {{ form.next_page }}
            {{ form.submit(class_="btn btn-primary") }}
        </form>
    </div>
{% endblock %}